### ISSUE TITLE
OK to convert README to rst?

### ISSUE THREAD

**Issue by matthew-brett** [cgwrench/rst2md#2]
I'm just writing a setup.py script for your useful module.   The long description field of the setup structure gets uploaded to pypi, and should be rst to get marked up correctly.   What I normally do is to read the README.rst file in as the long description, but the readme for rst2md is - markdown.

I was thinking it might be fun to convert the README to rst as the source format, then build the README.md using the rst2md script.

**Comment by cgwrench** [comment]
I'm more than happy to convert the project README to reStructuredText if it helps support a setup script. Although it could be fun to demostrate the conversion with the README, I don't think there would need to have two READMEs.

**Comment by matthew-brett** [comment]
OK - I'll do that as part of my current PR if I may.

**Comment by cgwrench** [comment]
Please feel free to. However, it may be best if this is submitted as a separate pull request: I would much rather recieve small pull requests that made a single change. This makes it far easier for me to review and more likely that I will be able to accept the change quickly.

**Comment by cgwrench** [comment]
Hi @matthew-brett. Please see my comment on #4. As noted there, I'm going to close this issue and mark the repository as read-only.

Once again, thanks for your contributions. And apologies for not giving them the attention they deserve.
